name: martianlantern

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: kramdown
highlighter: rouge
mathjax: true

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: plaintext
    block:
      line_numbers: false

url: https://martianlantern.github.io
permalink: /:year/:month/:title/
owner:
    name: martianlantern
    twitter: martianlantern
    github: martianlantern
    disqus_shortname: disqus_bG5evWWJUM

ga_id: #
ga_username: #

timezone: Asia/Kolkata
future: true